name: EAS Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install latest EAS CLI
        run: npm install -g eas-cli@latest

      - name: Create Java 17 env file for EAS
        run: |
          mkdir -p .eas
          echo '{ "ANDROID_BUILD_JAVA_HOME": "/opt/build/android/java/openjdk/jdk-17" }' > .eas/environment.json

      - name: Build APK with EAS
        run: eas build --platform android --profile production --non-interactive

      - name: Show build details
        run: eas build:list --limit 1 --json

