name: Build APK with Expo EAS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    name: EAS Build (APK)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Start Android build (APK)
        run: eas build --platform android --profile production --non-interactive

      - name: Show build details
        run: eas build:list --limit=1
