name: EAS Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install latest EAS CLI
        run: npm install -g eas-cli@latest

      - name: Build APK with EAS
        run: eas build --platform android --profile production --non-interactive

      - name: Get latest build info (JSON)
        id: get_apk_url
        run: |
          apk_url=$(eas build:list --platform android --limit 1 --json --non-interactive | jq -r '.[0].artifacts.buildUrl')
          echo "APK_URL=$apk_url" >> "$GITHUB_ENV"

      - name: Download APK
        run: |
          mkdir -p artifacts
          curl -L "$APK_URL" -o artifacts/my-app.apk

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: artifacts/my-app.apk